name: react_on_surge
on:
 push:
  branches:
  - react_app_deploy
jobs:
 build_job:
  name: build_job
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v2
   - name: build
     run: | 
      npm install
      npm run build
     working-directory: ./project
   - name: artifact
     uses: actions/upload-artifact@v2
     with:
      name: artifact
      path: ./project/build
 deploy_job:
  runs-on: ubuntu-latest
  needs: build_job
  steps:
    - name: artifact download
      uses: actions/download-artifact@v2
      with: 
        name: artifact
    - name: surge_deploy
      uses: dswistowski/surge-sh-action@v1
      with:
        domain: andanivicente.surge.sh
        project: .
        login: ${{secrets.SURGE_EMAIL }}
        token: ${{secrets.SURGE_TOKEN }}

